[package]
name = "graph-generator"
version = "0.1.0"
authors = ["Jack Stade <jack.stade@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"